# This workflow build and push a Docker container to Google Artifact Registry and deploy it on Cloud Run when a commit is pushed to the $default-branch branch
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Build a docker container
# 4. Publish it to Google Artifact Registry
# 5. Deploy it to Cloud Run
#
# To configure this workflow:
#
# 1. Ensure the required Google Cloud APIs are enabled:
#
#    Cloud Run            run.googleapis.com
#    Artifact Registry    artifactregistry.googleapis.com
#
# 2. Create and configure Workload Identity Federation for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Ensure the required IAM permissions are granted
#
#    Cloud Run
#      roles/run.admin
#      roles/iam.serviceAccountUser     (to act as the Cloud Run runtime service account)
#
#    Cloud Storage
#      roles/storage.admin   (if using Google Container Registry (gcr) instead)
#
#    Artifact Registry
#      roles/artifactregistry.admin     (project or repository level)
#
#    NOTE: You should always follow the principle of least privilege when assigning IAM roles
#
# 4. Create GitHub secrets for WIF_PROVIDER and WIF_SERVICE_ACCOUNT
#
# 5. Change the values for the GAR_LOCATION, SERVICE and REGION environment variables (below).
#
# NOTE: To use Google Container Registry instead, replace ${{ env.GAR_LOCATION }}-docker.pkg.dev with gcr.io
#
# For more support on how to run this workflow, please visit https://github.com/marketplace/actions/deploy-to-cloud-run
#
# Further reading:
#   Cloud Run IAM permissions                 - https://cloud.google.com/run/docs/deploying
#   Artifact Registry IAM permissions         - https://cloud.google.com/artifact-registry/docs/access-control#roles
#   Container Registry vs Artifact Registry   - https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
#   Principle of least privilege              - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege

name: Deploy GCP

# Shield url for README.md: 
# https://img.shields.io/github/workflow/status/GoogleCloudPlatform/github-actions/deploy-gcp?style=for-the-badge

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  # -----------------------------------------------------------------------------------------------
  # Verbose version for demonstration purposes.
  deploy-preview:

    name: Deploy Preview

    # Deploy to preview as test per every PR.
    if: ${{ github.event_name == 'pull_request' }}

    # IMPORTANT: 'environment' is repo-defined, 'env' is workflow-defined.
    environment: deploy-gcp-preview
    env:
      NEW_BACKEND_PREVIEW_IMAGE_NAME: ${{ vars.GCP_BACKEND_PREVIEW_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_BACKEND_PREVIEW_PROJECT_ID }}/${{ vars.GCP_BACKEND_PREVIEW_ARTIFACT_REGISTRY_NAME }}/${{ vars.GCP_BACKEND_PREVIEW_DOCKER_IMAGE_NAME}}:${{ github.sha }}

    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      # Avoid using 'main' since it might be unstable.
      - name: Checkout Code
        uses: 'actions/checkout@v4'

      # GCP auth using SA's credentials json
      - name: GCP Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_PREVIEW_DEPLOY_SERVICE_ACCOUNT_KEY_JSON }}'
          # IMPORTANT: 
          # Removed param "token_format: 'access_token'", deprecated and will cause auth error!

      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)
          
      # Docker (GCP Artifact Registry) auth using credentials json
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          registry: ${{ vars.GCP_BACKEND_PREVIEW_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_PREVIEW_DEPLOY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Docker Build and Push
        run: |-
          docker build -t "${{ env.NEW_BACKEND_PREVIEW_IMAGE_NAME }}" ./
          docker push "${{ env.NEW_BACKEND_PREVIEW_IMAGE_NAME }}"

      # END - Docker auth and build

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ vars.GCP_BACKEND_PREVIEW_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ vars.GCP_BACKEND_PREVIEW_CLOUD_RUN_SERVICE_REGION }}
          image: ${{ env.NEW_BACKEND_PREVIEW_IMAGE_NAME }}
          env_vars: |
            BACKEND_PORTPORT=${{ vars.BACKEND_PORT }}
            FIRESTORE_DATABASE_ID=${{ vars.PREVIEW_FIRESTORE_DATABASE_ID }}

      - name: Report Deployed URL to Actinons Log
        run: echo "Preview url at ${{ steps.deploy.outputs.url }}"

      - name: Report Deployed URL to PR
        uses: 'thollander/actions-comment-pull-request@v2'
        with:
          message: |
            To DEV's devops officer @KemingHe and the triggering person for this deployment @${{ github.triggering_actor }},

            The new preview of ${{ github.repository }} has been deployed and live at: 
              
            > ${{ steps.deploy.outputs.url }}

            **Please manully test the live preview as part of the PR review process.**

            Have a great day!

  # -----------------------------------------------------------------------------------------------
  # Concise production deployment job dev, only runs on push to main.
  deploy-production:

    name: Deploy Production

    if: ${{ github.event_name == 'push' &&  github.ref == 'refs/heads/main' }}

    environment: deploy-gcp-production
    env:
      NEW_BACKEND_PRODUCTION_IMAGE_NAME: ${{ vars.GCP_BACKEND_PRODUCTION_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_BACKEND_PRODUCTION_PROJECT_ID }}/${{ vars.GCP_BACKEND_PRODUCTION_ARTIFACT_REGISTRY_NAME }}/${{ vars.GCP_BACKEND_PRODUCTION_DOCKER_IMAGE_NAME}}:${{ github.sha }}

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: 'actions/checkout@v4'

      - name: GCP Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_PRODUCTION_DEPLOY_SERVICE_ACCOUNT_KEY_JSON }}'
    
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          registry: ${{ vars.GCP_BACKEND_PRODUCTION_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_PRODUCTION_DEPLOY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Docker Build and Push
        run: |-
          docker build -t "${{ env.NEW_BACKEND_PRODUCTION_IMAGE_NAME }}" ./
          docker push "${{ env.NEW_BACKEND_PRODUCTION_IMAGE_NAME }}"


      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ vars.GCP_BACKEND_PRODUCTION_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ vars.GCP_BACKEND_PRODUCTION_CLOUD_RUN_SERVICE_REGION }}
          image: ${{ env.NEW_BACKEND_PRODUCTION_IMAGE_NAME }}
          env_vars: |
            BACKEND_PORT=${{ vars.BACKEND_PORT }}
            FIRESTORE_DATABASE_ID=${{ vars.PRODUCTION_FIRESTORE_DATABASE_ID }}

      - name: Report Deployed URL to Actinons Log
        run: echo "Production url at ${{ steps.deploy.outputs.url }}"

      - name: Report Deployed URL as a New Issue
        uses: dacbd/create-issue-action@v2
        with:
          token: ${{ github.token }}
          title: ':rocket: New Production Deployment from ${{ github.sha }}'
          body: |
            To DEV's @technology team and the triggering person for this deployment @${{ github.triggering_actor }},

            The new production of ${{ github.repository }} has been deployed and live at: 
              
            > ${{ steps.deploy.outputs.url }}

            **Please reach out to keminghe.career[at]gmail.com for questions, otherwise, you can safely close this issue.**

            Have a great day!
